export enum ContentType {
  JSON = "application/json",
  TEXT = "text/plain",
  HTML = "text/html",
  XML = "application/xml",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  MULTIPART_FORM_DATA = "multipart/form-data",
  OCTET_STREAM = "application/octet-stream",
  PDF = "application/pdf",
  CSV = "text/csv",
  JPEG = "image/jpeg",
  PNG = "image/png",
  GIF = "image/gif",
  SVG = "image/svg+xml",
  WEBP = "image/webp",
  MP4 = "video/mp4",
  MPEG = "video/mpeg",
  MP3 = "audio/mpeg",
  WAV = "audio/wav"
}